server:
  port: 8004
  servlet:
    context-path: /

spring:
  application:
    name: search-service

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.socialw.search: DEBUG